services:
  api-principal:
    build: ./api-principal
    ports:
      - "8000:8000"
    environment:
      - SECONDARY_API_URL=http://api-secundaria:5000
    volumes:
      - api-principal-data:/app/data
    depends_on:
      - api-secundaria
    restart: unless-stopped

  api-secundaria:
    build: ./api-secundaria
    ports:
      - "5000:5000"
    volumes:
      - api-secundaria-data:/app/data
    restart: unless-stopped

volumes:
  api-principal-data:
  api-secundaria-data: